<?php

declare(strict_types=1);

namespace WPRC\Core\Content;

use WPRC\Core\Data\Content\PlaceholderContext;

defined('ABSPATH') || exit;

/**
 * WordPress integration for the shared placeholder engine.
 *
 * The block filter covers content blocks/patterns rendered outside the normal
 * post content pipeline. The content filter covers classic content and output
 * generated by shortcodes. Both paths are cheap for content without "[{".
 */
final class PlaceholderRenderer
{
    public function __construct(private readonly PlaceholderEngine $engine)
    {
    }

    public function init(): void
    {
        add_filter('render_block', [$this, 'renderBlock'], 99, 3);
        add_filter('the_content', [$this, 'renderContent'], 99);
        add_filter('widget_text_content', [$this, 'renderContent'], 99);
    }

    /**
     * @param array<string,mixed> $block
     */
    public function renderBlock(string $blockContent, array $block, ?\WP_Block $instance = null): string
    {
        if ((is_admin() && !wp_doing_ajax()) || $blockContent === '' || !str_contains($blockContent, '[{')) {
            return $blockContent;
        }

        $blockName = isset($block['blockName']) && is_string($block['blockName']) ? $block['blockName'] : null;
        $attributes = isset($block['attrs']) && is_array($block['attrs']) ? $block['attrs'] : [];

        return $this->engine->render(
            $blockContent,
            PlaceholderContext::current($blockName, $attributes)
        );
    }

    public function renderContent(string $content): string
    {
        if ((is_admin() && !wp_doing_ajax()) || $content === '' || !str_contains($content, '[{')) {
            return $content;
        }

        return $this->engine->render($content, PlaceholderContext::current());
    }
}
